# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/randy/workspace/rk3288/sysapps/rockchip-vdpau-driver

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/randy/workspace/rk3288/sysapps/rockchip-vdpau-driver

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/randy/workspace/rk3288/sysapps/rockchip-vdpau-driver/CMakeFiles /home/randy/workspace/rk3288/sysapps/rockchip-vdpau-driver/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/randy/workspace/rk3288/sysapps/rockchip-vdpau-driver/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vdpau_rockchip

# Build rule for target.
vdpau_rockchip: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vdpau_rockchip
.PHONY : vdpau_rockchip

# fast build rule for target.
vdpau_rockchip/fast:
	$(MAKE) -f CMakeFiles/vdpau_rockchip.dir/build.make CMakeFiles/vdpau_rockchip.dir/build
.PHONY : vdpau_rockchip/fast

# Manual pre-install relink rule for target.
vdpau_rockchip/preinstall:
	$(MAKE) -f CMakeFiles/vdpau_rockchip.dir/build.make CMakeFiles/vdpau_rockchip.dir/preinstall
.PHONY : vdpau_rockchip/preinstall

#=============================================================================
# Target rules for targets named rkdec

# Build rule for target.
rkdec: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rkdec
.PHONY : rkdec

# fast build rule for target.
rkdec/fast:
	$(MAKE) -f librkdec/CMakeFiles/rkdec.dir/build.make librkdec/CMakeFiles/rkdec.dir/build
.PHONY : rkdec/fast

decoder.o: decoder.c.o

.PHONY : decoder.o

# target to build an object file
decoder.c.o:
	$(MAKE) -f CMakeFiles/vdpau_rockchip.dir/build.make CMakeFiles/vdpau_rockchip.dir/decoder.c.o
.PHONY : decoder.c.o

decoder.i: decoder.c.i

.PHONY : decoder.i

# target to preprocess a source file
decoder.c.i:
	$(MAKE) -f CMakeFiles/vdpau_rockchip.dir/build.make CMakeFiles/vdpau_rockchip.dir/decoder.c.i
.PHONY : decoder.c.i

decoder.s: decoder.c.s

.PHONY : decoder.s

# target to generate assembly for a file
decoder.c.s:
	$(MAKE) -f CMakeFiles/vdpau_rockchip.dir/build.make CMakeFiles/vdpau_rockchip.dir/decoder.c.s
.PHONY : decoder.c.s

device.o: device.c.o

.PHONY : device.o

# target to build an object file
device.c.o:
	$(MAKE) -f CMakeFiles/vdpau_rockchip.dir/build.make CMakeFiles/vdpau_rockchip.dir/device.c.o
.PHONY : device.c.o

device.i: device.c.i

.PHONY : device.i

# target to preprocess a source file
device.c.i:
	$(MAKE) -f CMakeFiles/vdpau_rockchip.dir/build.make CMakeFiles/vdpau_rockchip.dir/device.c.i
.PHONY : device.c.i

device.s: device.c.s

.PHONY : device.s

# target to generate assembly for a file
device.c.s:
	$(MAKE) -f CMakeFiles/vdpau_rockchip.dir/build.make CMakeFiles/vdpau_rockchip.dir/device.c.s
.PHONY : device.c.s

gles.o: gles.c.o

.PHONY : gles.o

# target to build an object file
gles.c.o:
	$(MAKE) -f CMakeFiles/vdpau_rockchip.dir/build.make CMakeFiles/vdpau_rockchip.dir/gles.c.o
.PHONY : gles.c.o

gles.i: gles.c.i

.PHONY : gles.i

# target to preprocess a source file
gles.c.i:
	$(MAKE) -f CMakeFiles/vdpau_rockchip.dir/build.make CMakeFiles/vdpau_rockchip.dir/gles.c.i
.PHONY : gles.c.i

gles.s: gles.c.s

.PHONY : gles.s

# target to generate assembly for a file
gles.c.s:
	$(MAKE) -f CMakeFiles/vdpau_rockchip.dir/build.make CMakeFiles/vdpau_rockchip.dir/gles.c.s
.PHONY : gles.c.s

h264_decoder.o: h264_decoder.c.o

.PHONY : h264_decoder.o

# target to build an object file
h264_decoder.c.o:
	$(MAKE) -f CMakeFiles/vdpau_rockchip.dir/build.make CMakeFiles/vdpau_rockchip.dir/h264_decoder.c.o
.PHONY : h264_decoder.c.o

h264_decoder.i: h264_decoder.c.i

.PHONY : h264_decoder.i

# target to preprocess a source file
h264_decoder.c.i:
	$(MAKE) -f CMakeFiles/vdpau_rockchip.dir/build.make CMakeFiles/vdpau_rockchip.dir/h264_decoder.c.i
.PHONY : h264_decoder.c.i

h264_decoder.s: h264_decoder.c.s

.PHONY : h264_decoder.s

# target to generate assembly for a file
h264_decoder.c.s:
	$(MAKE) -f CMakeFiles/vdpau_rockchip.dir/build.make CMakeFiles/vdpau_rockchip.dir/h264_decoder.c.s
.PHONY : h264_decoder.c.s

handles.o: handles.c.o

.PHONY : handles.o

# target to build an object file
handles.c.o:
	$(MAKE) -f CMakeFiles/vdpau_rockchip.dir/build.make CMakeFiles/vdpau_rockchip.dir/handles.c.o
.PHONY : handles.c.o

handles.i: handles.c.i

.PHONY : handles.i

# target to preprocess a source file
handles.c.i:
	$(MAKE) -f CMakeFiles/vdpau_rockchip.dir/build.make CMakeFiles/vdpau_rockchip.dir/handles.c.i
.PHONY : handles.c.i

handles.s: handles.c.s

.PHONY : handles.s

# target to generate assembly for a file
handles.c.s:
	$(MAKE) -f CMakeFiles/vdpau_rockchip.dir/build.make CMakeFiles/vdpau_rockchip.dir/handles.c.s
.PHONY : handles.c.s

presentation_queue.o: presentation_queue.c.o

.PHONY : presentation_queue.o

# target to build an object file
presentation_queue.c.o:
	$(MAKE) -f CMakeFiles/vdpau_rockchip.dir/build.make CMakeFiles/vdpau_rockchip.dir/presentation_queue.c.o
.PHONY : presentation_queue.c.o

presentation_queue.i: presentation_queue.c.i

.PHONY : presentation_queue.i

# target to preprocess a source file
presentation_queue.c.i:
	$(MAKE) -f CMakeFiles/vdpau_rockchip.dir/build.make CMakeFiles/vdpau_rockchip.dir/presentation_queue.c.i
.PHONY : presentation_queue.c.i

presentation_queue.s: presentation_queue.c.s

.PHONY : presentation_queue.s

# target to generate assembly for a file
presentation_queue.c.s:
	$(MAKE) -f CMakeFiles/vdpau_rockchip.dir/build.make CMakeFiles/vdpau_rockchip.dir/presentation_queue.c.s
.PHONY : presentation_queue.c.s

rgba.o: rgba.c.o

.PHONY : rgba.o

# target to build an object file
rgba.c.o:
	$(MAKE) -f CMakeFiles/vdpau_rockchip.dir/build.make CMakeFiles/vdpau_rockchip.dir/rgba.c.o
.PHONY : rgba.c.o

rgba.i: rgba.c.i

.PHONY : rgba.i

# target to preprocess a source file
rgba.c.i:
	$(MAKE) -f CMakeFiles/vdpau_rockchip.dir/build.make CMakeFiles/vdpau_rockchip.dir/rgba.c.i
.PHONY : rgba.c.i

rgba.s: rgba.c.s

.PHONY : rgba.s

# target to generate assembly for a file
rgba.c.s:
	$(MAKE) -f CMakeFiles/vdpau_rockchip.dir/build.make CMakeFiles/vdpau_rockchip.dir/rgba.c.s
.PHONY : rgba.c.s

surface_bitmap.o: surface_bitmap.c.o

.PHONY : surface_bitmap.o

# target to build an object file
surface_bitmap.c.o:
	$(MAKE) -f CMakeFiles/vdpau_rockchip.dir/build.make CMakeFiles/vdpau_rockchip.dir/surface_bitmap.c.o
.PHONY : surface_bitmap.c.o

surface_bitmap.i: surface_bitmap.c.i

.PHONY : surface_bitmap.i

# target to preprocess a source file
surface_bitmap.c.i:
	$(MAKE) -f CMakeFiles/vdpau_rockchip.dir/build.make CMakeFiles/vdpau_rockchip.dir/surface_bitmap.c.i
.PHONY : surface_bitmap.c.i

surface_bitmap.s: surface_bitmap.c.s

.PHONY : surface_bitmap.s

# target to generate assembly for a file
surface_bitmap.c.s:
	$(MAKE) -f CMakeFiles/vdpau_rockchip.dir/build.make CMakeFiles/vdpau_rockchip.dir/surface_bitmap.c.s
.PHONY : surface_bitmap.c.s

surface_output.o: surface_output.c.o

.PHONY : surface_output.o

# target to build an object file
surface_output.c.o:
	$(MAKE) -f CMakeFiles/vdpau_rockchip.dir/build.make CMakeFiles/vdpau_rockchip.dir/surface_output.c.o
.PHONY : surface_output.c.o

surface_output.i: surface_output.c.i

.PHONY : surface_output.i

# target to preprocess a source file
surface_output.c.i:
	$(MAKE) -f CMakeFiles/vdpau_rockchip.dir/build.make CMakeFiles/vdpau_rockchip.dir/surface_output.c.i
.PHONY : surface_output.c.i

surface_output.s: surface_output.c.s

.PHONY : surface_output.s

# target to generate assembly for a file
surface_output.c.s:
	$(MAKE) -f CMakeFiles/vdpau_rockchip.dir/build.make CMakeFiles/vdpau_rockchip.dir/surface_output.c.s
.PHONY : surface_output.c.s

surface_video.o: surface_video.c.o

.PHONY : surface_video.o

# target to build an object file
surface_video.c.o:
	$(MAKE) -f CMakeFiles/vdpau_rockchip.dir/build.make CMakeFiles/vdpau_rockchip.dir/surface_video.c.o
.PHONY : surface_video.c.o

surface_video.i: surface_video.c.i

.PHONY : surface_video.i

# target to preprocess a source file
surface_video.c.i:
	$(MAKE) -f CMakeFiles/vdpau_rockchip.dir/build.make CMakeFiles/vdpau_rockchip.dir/surface_video.c.i
.PHONY : surface_video.c.i

surface_video.s: surface_video.c.s

.PHONY : surface_video.s

# target to generate assembly for a file
surface_video.c.s:
	$(MAKE) -f CMakeFiles/vdpau_rockchip.dir/build.make CMakeFiles/vdpau_rockchip.dir/surface_video.c.s
.PHONY : surface_video.c.s

v4l2.o: v4l2.c.o

.PHONY : v4l2.o

# target to build an object file
v4l2.c.o:
	$(MAKE) -f CMakeFiles/vdpau_rockchip.dir/build.make CMakeFiles/vdpau_rockchip.dir/v4l2.c.o
.PHONY : v4l2.c.o

v4l2.i: v4l2.c.i

.PHONY : v4l2.i

# target to preprocess a source file
v4l2.c.i:
	$(MAKE) -f CMakeFiles/vdpau_rockchip.dir/build.make CMakeFiles/vdpau_rockchip.dir/v4l2.c.i
.PHONY : v4l2.c.i

v4l2.s: v4l2.c.s

.PHONY : v4l2.s

# target to generate assembly for a file
v4l2.c.s:
	$(MAKE) -f CMakeFiles/vdpau_rockchip.dir/build.make CMakeFiles/vdpau_rockchip.dir/v4l2.c.s
.PHONY : v4l2.c.s

video_mixer.o: video_mixer.c.o

.PHONY : video_mixer.o

# target to build an object file
video_mixer.c.o:
	$(MAKE) -f CMakeFiles/vdpau_rockchip.dir/build.make CMakeFiles/vdpau_rockchip.dir/video_mixer.c.o
.PHONY : video_mixer.c.o

video_mixer.i: video_mixer.c.i

.PHONY : video_mixer.i

# target to preprocess a source file
video_mixer.c.i:
	$(MAKE) -f CMakeFiles/vdpau_rockchip.dir/build.make CMakeFiles/vdpau_rockchip.dir/video_mixer.c.i
.PHONY : video_mixer.c.i

video_mixer.s: video_mixer.c.s

.PHONY : video_mixer.s

# target to generate assembly for a file
video_mixer.c.s:
	$(MAKE) -f CMakeFiles/vdpau_rockchip.dir/build.make CMakeFiles/vdpau_rockchip.dir/video_mixer.c.s
.PHONY : video_mixer.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... vdpau_rockchip"
	@echo "... install/local"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... rkdec"
	@echo "... decoder.o"
	@echo "... decoder.i"
	@echo "... decoder.s"
	@echo "... device.o"
	@echo "... device.i"
	@echo "... device.s"
	@echo "... gles.o"
	@echo "... gles.i"
	@echo "... gles.s"
	@echo "... h264_decoder.o"
	@echo "... h264_decoder.i"
	@echo "... h264_decoder.s"
	@echo "... handles.o"
	@echo "... handles.i"
	@echo "... handles.s"
	@echo "... presentation_queue.o"
	@echo "... presentation_queue.i"
	@echo "... presentation_queue.s"
	@echo "... rgba.o"
	@echo "... rgba.i"
	@echo "... rgba.s"
	@echo "... surface_bitmap.o"
	@echo "... surface_bitmap.i"
	@echo "... surface_bitmap.s"
	@echo "... surface_output.o"
	@echo "... surface_output.i"
	@echo "... surface_output.s"
	@echo "... surface_video.o"
	@echo "... surface_video.i"
	@echo "... surface_video.s"
	@echo "... v4l2.o"
	@echo "... v4l2.i"
	@echo "... v4l2.s"
	@echo "... video_mixer.o"
	@echo "... video_mixer.i"
	@echo "... video_mixer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

